### ISSUE TITLE
Update the "Sending a message" tutorial to reference xcall-scaffolding repo

### ISSUE THREAD

**Issue by han-so1omon** [icon-project/xcall.dev#16]
As [xcall-scaffolding](https://github.com/icon-project/xcall-scaffolding) is the canonical sample repo for xcall, the ["Sending a message" tutorial](https://www.xcall.dev/quickstart/sending-a-message) must reference this repository. Currently, the tutorial references the [xcall-sample-dapp](https://github.com/icon-community/DAppProxySampleUtilityFunctions) repo, which has been recently modified and now serves a different purpose

In order to send a message with the canonical sample dApp, the sections for ["Sending a message"](https://www.xcall.dev/quickstart/sending-a-message#sending-a-message) and ["Sending a message with rollback"](https://www.xcall.dev/quickstart/sending-a-message-with-rollback) should be updated to reference the public functions that perform cross-chain messages (e.g. `voteYes`)

Alternatively, a new docs page may be put in to detail working with the canonical app, in which case the existing page should be edited to more clearly use the updated DAppProxySampleUtilityFunctions repository in conjunction with the e2edemo dapp sample

Also, the prerequisite link on [this page](https://www.xcall.dev/quickstart/sending-a-message-with-rollback) does not work

**Comment by han-so1omon** [comment]
[Sending a message" guide](https://www.xcall.dev/guides/sending-a-message) should probably be updated too, as well as the quickstart

**Comment by CyrusVorwald** [comment]
The purpose of https://github.com/icon-community/DAppProxySampleUtilityFunctions and related guides is to demonstrate how to programmatically interact with [DAppProxySample.sol](https://github.com/icon-project/btp2/blob/main/e2edemo/solidity/contracts/dapp-sample/DAppProxySample.sol) and its Java equivalent.

The purpose of xcall-scaffolding is to provide a template repository to be forked from.

So your alternative suggestion to create a separate page is the best path forward for now.

Later on, these may be consolidated. For example, the programmatic interactions could also be in xcall-scaffolding. This was only published yesterday so it will take a bit of time.

**Comment by CyrusVorwald** [comment]
Closing this as resolved by https://github.com/icon-project/xcall.dev/pull/6
